version: 2.1
jobs:
  test-locally:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/circle-ci-node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
